name: Build APK

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          workdir: .  # اگر buildozer.spec در ریشه است
          buildozer_version: stable

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: ${{ steps.buildozer.outputs.filename }}
